CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    app_access_token VARCHAR(100) NOT NULL,
    foursquare_access_token VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (app_access_token)
);